### ISSUE TITLE
DirectFB-1.7 branch and tags

### ISSUE THREAD

**Issue by ilyesgouta** [deniskropp/DirectFB#2]
Hi Denis,

Is it possible to also push the directfb-1.7 branch and the various release tags?

Best regards,
Ilyes

**Comment by deniskropp** [comment]
Ok will do later
Am 20.10.2015 10:23 schrieb "Ilyes Gouta" <notifications@github.com>:

**Comment by ilyesgouta** [comment]
Thanks Denis!

It looks like the directfb-1.7 branch is incomplete vs. what has been hosted on directfb.org .. Also is it possible to also push the DIRECTFB_1_7_7 tag?

Best regards,
Ilyes

**Comment by lgammo** [comment]
I second this request. 

Thanks Denis.

**Comment by tamaskoloti** [comment]
+1

**Comment by lancebaiyouview** [comment]
+1

**Comment by spencexu** [comment]
+1

**Comment by rossburton** [comment]
+1.  If this is meant to be the official home of directfb moving forwards, then actually having the latest release in git would be somewhat useful.

**Comment by Vaelatern** [comment]
+1

**Comment by maxinbjohn** [comment]
+1 .. 
This will help us on deciding whether to keep directfb in our project or not.

**Comment by ilyesgouta** [comment]
Hi,

I forked the repository and pushed the most (by then) up-to-date tags, as they were published on directfb.org, to:

https://github.com/ilyesgouta/DirectFB/tree/master-2
https://github.com/ilyesgouta/DirectFB/tree/directfb-1.7

Hopefully Denis will update the official repository accordingly.

Best regards,
Ilyes

**Comment by deniskropp** [comment]
I pushed 1.7.7 changes and tags.

**Comment by ilyesgouta** [comment]
Indeed, and hence closing the ticket.

Best regards,
Ilyes
