### ISSUE TITLE
Problems with doublebuffering

### ISSUE THREAD

**Issue by lonep** [deniskropp/DirectFB#23]
Hello,
i have some problems with double buffering. I use directfb on POS terminal.

My code looks like 
clear()
....
surf->drawSomething
....
flip()

but after call clear() i see white empty screen before flip() calling. It's looks like directFB using only front buffer for render.

If you have a copy of the original documentation, I would really appreciate it.

**Comment by lonep** [comment]
Problem solved, but if you have athe documentation is wider than it is now in the repository, I will be grateful

**Comment by bassklampfe** [comment]
Could you share the solution? Thanks.

**Comment by lonep** [comment]
I had mistace in surf render logic. I tried to render surface twice and due to my screen is blinking.
